#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KinoStatistics.Droid.Resource", IsApplication=true)]

namespace KinoStatistics.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::KinoStatistics.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::KinoStatistics.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::KinoStatistics.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::KinoStatistics.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::KinoStatistics.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::KinoStatistics.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::KinoStatistics.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::KinoStatistics.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::KinoStatistics.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::KinoStatistics.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::KinoStatistics.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::KinoStatistics.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::KinoStatistics.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::KinoStatistics.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::KinoStatistics.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::KinoStatistics.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::KinoStatistics.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::KinoStatistics.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::KinoStatistics.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::KinoStatistics.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::KinoStatistics.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::KinoStatistics.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::KinoStatistics.Droid.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.left_arrow = global::KinoStatistics.Droid.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.right_arrow = global::KinoStatistics.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.title = global::KinoStatistics.Droid.Resource.Id.title;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::KinoStatistics.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::KinoStatistics.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::KinoStatistics.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::KinoStatistics.Droid.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.week = global::KinoStatistics.Droid.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::KinoStatistics.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::KinoStatistics.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::KinoStatistics.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::KinoStatistics.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::KinoStatistics.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::KinoStatistics.Droid.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::KinoStatistics.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::KinoStatistics.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::KinoStatistics.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::KinoStatistics.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::KinoStatistics.Droid.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::KinoStatistics.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::KinoStatistics.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000a
			public const int calendar_active_month_bg = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int calendar_bg = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int calendar_divider = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int calendar_highlighted_day_bg = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int calendar_inactive_month_bg = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int calendar_selected_day_bg = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int calendar_selected_range_bg = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int calendar_text_active = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int calendar_text_inactive = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int calendar_text_selected = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int calendar_text_selector = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int calendar_text_unselectable = 2131099668;
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f060016
			public const int common_signin_btn_text_dark = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int common_signin_btn_text_light = 2131099671;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int calendar_day_headers_paddingbottom = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int calendar_month_title_bottommargin = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int calendar_month_topmargin = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int calendar_text_medium = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int calendar_text_small = 2131296260;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int avc = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar_bg_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_full_open_on_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_ic_googleplayservices = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_disabled_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_disabled_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_focus_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_focus_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_normal_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_normal_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_pressed_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_pressed_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_disabled_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_disabled_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_disabled_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_focus_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_focus_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_normal_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_normal_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_pressed_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_pressed_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int kinoball = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ksanalyze = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ksarrowright = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ksclock2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ksdeltio1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ksengine = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int kshelp = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int kshelp3 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int kskinologo = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int kslove = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ksmail = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ksnowifi = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ksrefresh = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int kssortdown = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int kssortup = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int kstablekino = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a0007
			public const int calendar_grid = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int calendar_view = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int left_arrow = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0005
			public const int right_arrow = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int title = 2131361795;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int month = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gtm_analytics = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050029
			public const int ApplicationName = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int Hello = 2131034152;
			
			// aapt resource value: 0x7f050024
			public const int accept = 2131034148;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int common_android_wear_notification_needs_update_text = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int common_android_wear_update_text = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int common_android_wear_update_title = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_api_unavailable_text = 2131034143;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_enable_button = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_enable_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_enable_title = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_install_button = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_install_text_phone = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_install_text_tablet = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_install_title = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_invalid_account_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_invalid_account_title = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_needs_enabling_title = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_network_error_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_network_error_title = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_notification_needs_update_title = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_notification_ticker = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int common_google_play_services_sign_in_failed_text = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int common_google_play_services_sign_in_failed_title = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_unknown_issue = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_unsupported_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_unsupported_title = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_update_button = 2131034139;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_text = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_update_title = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_updating_text = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_updating_title = 2131034130;
			
			// aapt resource value: 0x7f05001e
			public const int common_open_on_phone = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int common_signin_button_text = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int common_signin_button_text_long = 2131034141;
			
			// aapt resource value: 0x7f050027
			public const int create_calendar_message = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int create_calendar_title = 2131034150;
			
			// aapt resource value: 0x7f05002b
			public const int day_name_format = 2131034155;
			
			// aapt resource value: 0x7f050025
			public const int decline = 2131034149;
			
			// aapt resource value: 0x7f05002e
			public const int full_date_format = 2131034158;
			
			// aapt resource value: 0x7f05002c
			public const int invalid_date = 2131034156;
			
			// aapt resource value: 0x7f05002a
			public const int library_name = 2131034154;
			
			// aapt resource value: 0x7f05002d
			public const int month_name_format = 2131034157;
			
			// aapt resource value: 0x7f050023
			public const int store_picture_message = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int store_picture_title = 2131034146;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int CalendarCell = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int CalendarCell_CalendarDate = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int CalendarCell_DayHeader = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int CalendarTitle = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Theme_IAPTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
